-- MySQL Script generated by MySQL Workbench
-- 02/02/17 10:50:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aseguradora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aseguradora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aseguradora` DEFAULT CHARACTER SET utf8 ;
USE `aseguradora` ;

-- -----------------------------------------------------
-- Table `aseguradora`.`aseguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`aseguradora` (
  `rif` INT(11) NOT NULL,
  `cuentabancaria` VARCHAR(45) NULL,
  `cedulacuentabancaria` INT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `telefonolocal` VARCHAR(45) NULL DEFAULT NULL,
  `telefonopersonal` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'INACTIVA',
  `estado` VARCHAR(45) NULL,
  `fechafundacion` DATE NULL,
  PRIMARY KEY (`rif`),
  UNIQUE INDEX `rif_UNIQUE` (`rif` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`corredor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`corredor` (
  `cedula` INT(10) UNSIGNED NOT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fechanacimiento` DATE NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `fecharegistro` DATE NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'INACTIVO',
  `aseguradora_rif` INT(11) NOT NULL,
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  INDEX `fk_Asegurador_Aseguradora1_idx` (`aseguradora_rif` ASC),
  CONSTRAINT `fk_Asegurador_Aseguradora1`
    FOREIGN KEY (`aseguradora_rif`)
    REFERENCES `aseguradora`.`aseguradora` (`rif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`asegurado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`asegurado` (
  `cedula` INT(10) UNSIGNED NOT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fechanacimiento` DATE NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'SIN ASEGURAR',
  `estado` INT(11) NULL DEFAULT '1',
  `corredor_cedula` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  INDEX `fk_Asegurado_Corredor1_idx` (`corredor_cedula` ASC),
  CONSTRAINT `fk_Asegurado_Corredor1`
    FOREIGN KEY (`corredor_cedula`)
    REFERENCES `aseguradora`.`corredor` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`beneficiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`beneficiario` (
  `cedula` INT(10) UNSIGNED NOT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fechanacimiento` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'SIN ASIGNAR',
  `asegurado_cedula` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  INDEX `fk_beneficiario_Asegurado1_idx` (`asegurado_cedula` ASC),
  CONSTRAINT `fk_beneficiario_Asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`tipopolizas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`tipopolizas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `costo` VARCHAR(45) NULL DEFAULT NULL,
  `cobertura` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`tiposeguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`tiposeguro` (
  `codigo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `id_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`servicio` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `fechaadquisicion` DATE NULL DEFAULT NULL,
  `fechavigencia` DATE NULL DEFAULT NULL,
  `fechaculminacion` DATE NULL DEFAULT NULL,
  `beneficios` VARCHAR(45) NULL DEFAULT NULL,
  `monto` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'SIN ADQUIRIR',
  `cobertura` VARCHAR(45) NULL DEFAULT 'NACIONAL',
  `observaciones` VARCHAR(100) NULL DEFAULT NULL,
  `tipopolizas_codigo` INT(11) NOT NULL,
  `tiposeguro_codigo` INT(11) NOT NULL,
  `asegurado_cedula` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`, `tipopolizas_codigo`, `asegurado_cedula`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_Servicio_tipopolizas1_idx` (`tipopolizas_codigo` ASC),
  INDEX `fk_servicio_tiposeguro1_idx` (`tiposeguro_codigo` ASC),
  INDEX `fk_servicio_asegurado1_idx` (`asegurado_cedula` ASC),
  CONSTRAINT `fk_Servicio_tipopolizas1`
    FOREIGN KEY (`tipopolizas_codigo`)
    REFERENCES `aseguradora`.`tipopolizas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_tiposeguro1`
    FOREIGN KEY (`tiposeguro_codigo`)
    REFERENCES `aseguradora`.`tiposeguro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`factura` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `montototal` VARCHAR(45) NULL DEFAULT NULL,
  `montocancelado` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT 'SIN CANCELAR',
  `observaciones` VARCHAR(100) NULL DEFAULT NULL,
  `aseguradora_rif` INT(11) NOT NULL,
  `servicio_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `aseguradora_rif`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_Factura_Aseguradora1_idx` (`aseguradora_rif` ASC),
  INDEX `fk_Factura_Servicio1_idx` (`servicio_codigo` ASC),
  CONSTRAINT `fk_Factura_Aseguradora1`
    FOREIGN KEY (`aseguradora_rif`)
    REFERENCES `aseguradora`.`aseguradora` (`rif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Servicio1`
    FOREIGN KEY (`servicio_codigo`)
    REFERENCES `aseguradora`.`servicio` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`gastos` (
  `codigo` VARCHAR(45) NOT NULL,
  `asegurado_cedula` INT(10) UNSIGNED NOT NULL,
  `monto` VARCHAR(45) NULL DEFAULT NULL,
  `reembolso` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_Gastos_Asegurado1_idx` (`asegurado_cedula` ASC),
  CONSTRAINT `fk_Gastos_Asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`pagos_de_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`pagos_de_servicios` (
  `servicio_codigo` INT(11) NOT NULL,
  `servicio_tipopolizas_codigo` INT(11) NOT NULL,
  `asegurado_cedula` INT(10) UNSIGNED NOT NULL,
  `factura_codigo` INT(11) NOT NULL,
  `factura_Aseguradora_rif` INT(11) NOT NULL,
  PRIMARY KEY (`servicio_codigo`, `servicio_tipopolizas_codigo`, `asegurado_cedula`),
  INDEX `fk_Servicio_has_Asegurado_Asegurado1_idx` (`asegurado_cedula` ASC),
  INDEX `fk_Servicio_has_Asegurado_Servicio1_idx` (`servicio_codigo` ASC, `servicio_tipopolizas_codigo` ASC),
  INDEX `fk_pagos_de_servicios_Factura1_idx` (`factura_codigo` ASC, `factura_Aseguradora_rif` ASC),
  CONSTRAINT `fk_Servicio_has_Asegurado_Asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicio_has_Asegurado_Servicio1`
    FOREIGN KEY (`servicio_codigo` , `servicio_tipopolizas_codigo`)
    REFERENCES `aseguradora`.`servicio` (`codigo` , `tipopolizas_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_de_servicios_Factura1`
    FOREIGN KEY (`factura_codigo` , `factura_Aseguradora_rif`)
    REFERENCES `aseguradora`.`factura` (`codigo` , `aseguradora_rif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`polizas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`polizas` (
  `corredor_cedula` INT(10) UNSIGNED NOT NULL,
  `tipopolizas_codigo` INT(11) NOT NULL,
  `asegurado_cedula` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`asegurado_cedula`),
  INDEX `fk_polizas_Corredor1_idx` (`corredor_cedula` ASC),
  INDEX `fk_polizas_tipopolizas1_idx` (`tipopolizas_codigo` ASC),
  CONSTRAINT `fk_polizas_Asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_polizas_Corredor1`
    FOREIGN KEY (`corredor_cedula`)
    REFERENCES `aseguradora`.`corredor` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_polizas_tipopolizas1`
    FOREIGN KEY (`tipopolizas_codigo`)
    REFERENCES `aseguradora`.`tipopolizas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`reembolsos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`reembolsos` (
  `asegurado_cedula` INT(10) UNSIGNED NOT NULL,
  `monto` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` VARCHAR(45) NULL DEFAULT NULL,
  `gastos_codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`asegurado_cedula`, `gastos_codigo`),
  INDEX `fk_indemnizacion_Gastos1_idx` (`gastos_codigo` ASC),
  CONSTRAINT `fk_Reembolsos_Asegurado1`
    FOREIGN KEY (`asegurado_cedula`)
    REFERENCES `aseguradora`.`asegurado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indemnizacion_Gastos1`
    FOREIGN KEY (`gastos_codigo`)
    REFERENCES `aseguradora`.`gastos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aseguradora`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aseguradora`.`usuarios` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `direccion` VARCHAR(20) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `salt` CHAR(28) NOT NULL,
  `cedula` INT(10) NOT NULL,
  `nivel` INT(1) NOT NULL,
  `cookie` INT(10) NOT NULL,
  `logueado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
